server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
---
spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud GateWay Globar Filter with chan
            preLogger: true
            postLogger: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
          - Path=/user-service/**
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/**

          filters:
            - name: CustomFilter
        #              args:
        #                baseMessage: this is CustomFilterExample
        #                    - AddRequestHeader=first-request, first-request-header
        #                    - AddResponseHeader=first-response, first-response-header

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
          filters:
            - CustomFilter

#            - AddRequestHeader=second-request, second-request-header
#            - AddResponseHeader=second-response, second-response-header
